In [1]:
#Decomposição LU
#Decomposição de Cholesky
#Procedimento iterativo de Jacobi
#Procedimento iterativo de Gauss-Seidel

In [19]:
import numpy as np
from scipy import linalg

In [20]:
A = np.array([[1, 2, 2],
              [4, 4, 2],
              [4, 6, 4]])

In [21]:
b = np.array([3, 6, 10]).reshape(-1, 1)

In [22]:
def decomposicao_lu(A):
    n = A.shape[0]

    L = np.eye(n, dtype=np.double)
    
    for i in range(n):
        factor = A[i+1:, i]/A[i, i]
        L[i+1:, i] = factor
        A[i+1:] = A[i+1:] - factor[:, np.newaxis] * A[i]
    
    return L, A

In [23]:
L, U = decomposicao_lu(A)

In [24]:
print("L:")
display(L)
print("\n----\n")
print("U:")
display(U)

L:


array([[1. , 0. , 0. ],
       [4. , 1. , 0. ],
       [4. , 0.5, 1. ]])


----

U:


array([[ 1,  2,  2],
       [ 0, -4, -6],
       [ 0,  0, -1]])

In [32]:
def resolve_lu(L, U, b):
    n = b.shape[0]
    y = np.zeros((n,1))
    x = np.zeros((n,1))
    
    y[0][0] = b[0][0]/L[0, 0]
    
    for i in range(2, n+1):
        y[i-1][0] = (b[i-1][0] - sum(L[i-1, j-1]*y[j-1][0] for j in range(1, i)))/L[i-1, i-1]

    
    x[n-1][0] = y[n-1][0]/U[n-1, n-1]
    
    for i in reversed(range(1, n)):
        x[i-1][0] = (y[i-1][0] - sum(U[i-1, j-1]*x[j-1][0] for j in range(i+1, n+1)))/U[i-1, i-1] 

    
    return x

In [33]:
x = resolve_lu(L, U, b)

In [34]:
x

array([[-1.],
       [ 3.],
       [-1.]])

In [19]:
x

array([10.,  6., -2.])

In [ ]:
A_new

In [ ]:
L

In [ ]:
U

In [ ]:
np.zeros((4, 4))

In [ ]:
i, j = A.shape

In [ ]:
j

In [2]:
import pandas as pd

In [26]:
df = pd.read_table("../src/matrix_A_sample.txt", header=None,sep=" ")

In [27]:
df.to_numpy()

array([[1, 2, 2],
       [4, 4, 2],
       [4, 6, 4]])

In [32]:
with open('../src/matrix_A_sample.txt', 'r') as f:
    a = f.read()

In [34]:
a.encode()

b'1 2 2\n4 4 2\n4 6 4'

In [8]:
latex_string = r""""""

In [9]:
latex_string += "a"

In [5]:
latex_string.append("a")

AttributeError: 'str' object has no attribute 'append'

In [10]:
latex_string

'a'