In [1]:
import numpy as np

In [2]:
A = np.array([
    [3, -1, -1],
    [-1, 3, -1],
    [-1, -1, 3]
])

In [16]:
np.linalg.norm(b)

2.449489742783178

In [13]:
b = np.array([1, 2, 1])
b = b.reshape(-1, 1)

In [14]:
np.ones(b.shape)

array([[1.],
       [1.],
       [1.]])

In [41]:
def resolve_jacobi(A, b, tol=10**-3):
    
    n = A.shape[0]
    
    R = np.inf
    x_new = np.ones(b.shape)
    
    while (R > tol):
        x_old = x_new
        x_new = np.zeros(b.shape)
        
        for i in range(1, n+1):
            x_new[i-1][0] = (b[i-1][0] - sum([A[i-1][j-1]*x_old[j-1][0] for j in range(1, n+1) if j is not i]))/A[i-1][i-1]
            R = np.linalg.norm(x_new - x_old)/np.linalg.norm(x_new)
            
    return x_new
        

In [46]:
x = resolve_jacobi(A, b, tol=10**-3)

In [47]:
x

array([[1.24743104],
       [1.49743057],
       [1.24743104]])

In [48]:
# Critério de convergência: A matriz A deve ser diagonal dominante

In [53]:
def tem_diagonal_dominante(A):
    D = np.diag(np.abs(A))
    S = np.sum(np.abs(A), axis=1) - D
    print(D)
    print(S)
    if np.all(D > S):
        print("Matriz tem diagonal dominante")
    else:
        print("Matriz não tem diagonal dominante")

In [54]:
tem_diagonal_dominante(A)

[3 3 3]
[2 2 2]
Matriz tem diagonal dominante
