In [1]:
import numpy as np

In [2]:
import pandas as pd

In [36]:
np.all(A)

True

True

In [37]:
A = np.array([
    [3, -1, -1],
    [-1, np.nan, -1],
    [-1, -1, 3]
])

In [42]:
np.round(A, 3)

array([[ 3., -1., -1.],
       [-1., nan, -1.],
       [-1., -1.,  3.]])

In [4]:
b = np.array([1, 2, 1])
b = b.reshape(-1, 1)

In [14]:
np.linalg.det(A)

16.000000000000007

In [9]:
A

array([[ 3, -1, -1],
       [-1,  3, -1],
       [-1, -1,  3]])

In [8]:
b

array([[1],
       [2],
       [1]])

In [10]:
def tem_diagonal_dominante(A):
    D = np.diag(np.abs(A))
    S = np.sum(np.abs(A), axis=1) - D
    if np.all(D > S):
        return True
    else:
        return False

In [11]:
def resolve_gauss_seidel(A, b, tol=10**-13):
    if not tem_diagonal_dominante(A):
        raise Exception("Matriz A não tem diagonal dominante.")
    
    n = A.shape[0]
    
    R = np.inf
    x_new = np.ones(b.shape)
    while (R > tol):
        x_old = x_new
        x_new = np.zeros(b.shape)
        
        for i in range(1, n+1):
            x_new[i-1][0] = (b[i-1][0]- sum([A[i-1][j-1]*x_new[j-1][0] for j in range(1, i)]) - sum([A[i-1][j-1]*x_old[j-1][0] for j in range(i+1, n+1)]))/A[i-1, i-1]
            R = np.linalg.norm(x_new - x_old)/np.linalg.norm(x_new)
            
    return x_new

In [12]:
x = resolve_gauss_seidel(A, b, tol=10**-3)

In [13]:
x

array([[1.24911369],
       [1.49931968],
       [1.24947779]])

In [14]:
#Convergência: Mesmas condições do método de Jacobi, porém, se a matriz for simétrica e positiva definida 
# a convergência é sempre garantida

In [17]:
def verificar_simetria(A):
    if (A == A.T).all():
        print("Matriz é simétrica")
    else:
        print("Matriz não é simétrica")

In [18]:
verificar_simetria(A)

Matriz é simétrica


In [19]:
def verificar_positiva_definida(A):
    if np.all(np.linalg.eigvals(A) > 0):
        print("Matriz é positiva definida")
    else:
        print("Matriz não é positiva definida")

In [20]:
verificar_positiva_definida(A)

Matriz é positiva definida
