In [22]:
import numpy as np

In [74]:
A = np.array([
    [1, 0.2, 0],
    [0.2, 1, 0.5],
    [0, 0.5, 1]
])

In [75]:
X = np.eye(*A.shape)
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
def verificar_simetria(A):
    if (A == A.T).all():
        return True
    else:
        return False

In [10]:
def indices_maximo_valor(A):
    n = A.shape[0]
    
    max_valor = np.NINF
    p, q = (np.nan, np.nan)
    
    
    for i in range(1, n+1):
        for j in range(i+1, n+1):
            if np.abs(A[i-1][j-1]) > max_valor:
                max_valor = np.abs(A[i-1][j-1])
                p, q = i, j
    
    return p, q

In [14]:
def calcula_phi(A, p, q):
    if A[p-1][p-1] == A[q-1][q-1]:
        phi = np.pi/4
    else:
        phi = np.arctan(2*A[p-1][q-1]/(A[p-1][p-1]-A[q-1][q-1]))/2
    return phi

In [12]:
def cria_matriz_p(phi, n, p, q):
    P = np.eye(n, n)
    
    P[p-1][p-1] = np.cos(phi)
    P[p-1][q-1] = -np.sin(phi)
    P[q-1][p-1] = np.sin(phi)
    P[q-1][q-1] = np.cos(phi)
    
    return P

In [64]:
np.all([True, False])

False

In [65]:
def checar_tol(A, tol):
    return np.all([np.abs(A[i-1][j-1]) < tol for i in range(1, A.shape[0]+1) for j in range(1, A.shape[0]+1) if i != j])

In [70]:
z = np.array([[3, 3],
              [1, 1]])

In [71]:
checar_tol(z, 2)

False

In [15]:
p, q = indices_maximo_valor(A)
p, q

(2, 3)

In [16]:
phi = calcula_phi(A, p, q)
phi

0.7853981633974483

In [41]:
P = cria_matriz_p(phi, A.shape[0], p, q)
P

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  0.70710678,  0.70710678]])

In [47]:
A_2 = np.matmul(P.T, A)
A_2 = np.matmul(A_2, P)
A_2

array([[ 1.00000000e+00,  1.41421356e-01, -1.41421356e-01],
       [ 1.41421356e-01,  1.50000000e+00, -1.52198045e-17],
       [-1.41421356e-01,  8.96901945e-17,  5.00000000e-01]])

In [43]:
X_2 = np.matmul(X, P)
X_2

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  0.70710678,  0.70710678]])

In [49]:
p, q = indices_maximo_valor(A_2)
p, q

(1, 2)

In [50]:
phi = calcula_phi(A_2, p, q)
phi

-0.25740297755990543

In [51]:
P = cria_matriz_p(phi, A_2.shape[0], p, q)
P

array([[ 0.96705436,  0.25456995,  0.        ],
       [-0.25456995,  0.96705436,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [52]:
A_3 = np.matmul(P.T, A_2)
A_3 = np.matmul(A_3, P)
A_3

array([[ 9.62771868e-01,  1.80261375e-17, -1.36762139e-01],
       [ 2.93125329e-17,  1.53722813e+00, -3.60016278e-02],
       [-1.36762139e-01, -3.60016278e-02,  5.00000000e-01]])

In [89]:
def jacob_eigen(A, tol=10**-8):
    
    if not verificar_simetria(A):
        print("Não pode.")
    
    n = A.shape[0]
    
    X = np.eye(*A.shape)
    
    while True:
        p, q = indices_maximo_valor(A)
        phi = calcula_phi(A, p, q)
        P = cria_matriz_p(phi, n, p, q)
        
        A = np.matmul(P.T, A)
        A = np.matmul(A, P)
        
        X = np.matmul(X, P)
        
        if checar_tol(A, tol):
            return A, X

In [90]:
A_, X_ = jacob_eigen(A, tol=10**-8)

In [92]:
np.round(A_, 3)

array([[ 1.   ,  0.   , -0.   ],
       [ 0.   ,  1.539, -0.   ],
       [-0.   ,  0.   ,  0.461]])

In [94]:
np.round(X_, 3)

array([[ 0.928,  0.263,  0.263],
       [ 0.   ,  0.707, -0.707],
       [-0.371,  0.657,  0.657]])

In [100]:
try:
    raise Exception("Matriz não é simétrica")
    
except Exception as err:
    print(err)

Matriz não é simétrica


In [88]:
verificar_simetria(A)

True