In [1]:
#Decomposição LU
#Decomposição de Cholesky
#Procedimento iterativo de Jacobi
#Procedimento iterativo de Gauss-Seidel

In [2]:
import numpy as np
from scipy import linalg

In [3]:
A = np.array([[1, 2, 2],
              [4, 4, 2],
              [4, 6, 4]])

In [4]:
b = np.array([3, 6, 10])

In [5]:
def decomposicao_lu(A):
    n = A.shape[0]

    L = np.eye(n, dtype=np.double)
    
    for i in range(n):
        factor = A[i+1:, i]/A[i, i]
        L[i+1:, i] = factor
        A[i+1:] = A[i+1:] - factor[:, np.newaxis] * A[i]
    
    return L, A

In [6]:
L, U = decomposicao_lu(A)

In [7]:
print("L:")
display(L)
print("\n----\n")
print("U:")
display(U)

L:


array([[1. , 0. , 0. ],
       [4. , 1. , 0. ],
       [4. , 0.5, 1. ]])


----

U:


array([[ 1,  2,  2],
       [ 0, -4, -6],
       [ 0,  0, -1]])

In [14]:
def resolve_lu(L, U, b):
    n = len(b)
    y = np.zeros(n)
    x = np.zeros(n)
    
    y[0] = b[0]/L[0, 0]
    
    for i in range(2, n+1):
        soma = 0
        for j in range(1, i):
            soma += L[i-1, j-1]*y[j-1]
        y[i-1] = (b[i-1] - soma)/L[i-1, i-1]

    
    x[n-1] = y[n-1]/U[n-1, n-1]
    print(x[n-1])
    
    for i in reversed(range(1, n)):
        soma = 0
        for j in range(i+1, n+1):
            soma += U[i-1, j-1]*x[j-1]
        x[i-1] = (y[i-1] - soma)/U[i-1, i-1] 

    
    return x

In [15]:
x = resolve_lu(L, U, b)

-1.0


In [16]:
x

array([-1.,  3., -1.])

In [19]:
x

array([10.,  6., -2.])

In [ ]:
A_new

In [ ]:
L

In [ ]:
U

In [ ]:
np.zeros((4, 4))

In [ ]:
i, j = A.shape

In [ ]:
j

In [17]:
import pandas as pd

In [26]:
df = pd.read_table("../src/matrix_A_sample.txt", header=None,sep=" ")

In [27]:
df.to_numpy()

array([[1, 2, 2],
       [4, 4, 2],
       [4, 6, 4]])

In [28]:
pd.read_csv("../src/matrix_A_sample.txt")

1 2 2
0  4 4 2
1  4 6 4

In [32]:
with open('../src/matrix_A_sample.txt', 'r') as f:
    a = f.read()

In [34]:
a.encode()

b'1 2 2\n4 4 2\n4 6 4'